"""
LAYER 7: Deterministic Opentrons Compiler
Converts verified IR directly to executable Opentrons Python code.
"""

from typing import List
from protocolir.schemas import IROp, IROpType


def compile_to_opentrons(ir_ops: List[IROp]) -> str:
    """
    Compile IR operations to Opentrons Python script.

    Args:
        ir_ops: List of verified IR operations

    Returns:
        Executable Opentrons Python script as string
    """

    script = [
        "from opentrons import protocol_api",
        "",
        "metadata = {",
        '    "apiLevel": "2.14",',
        '    "protocolName": "ProtocolIR Generated Protocol",',
        '    "description": "Auto-generated by ProtocolIR"',
        "}",
        "",
        "def run(protocol: protocol_api.ProtocolContext):",
    ]

    # Track what's been loaded
    loaded_labware = {}
    loaded_instruments = {}

    for op in ir_ops:
        if op.op == IROpType.LOAD_LABWARE:
            alias = op.alias
            opentrons_name = op.opentrons_name
            slot = op.slot
            script.append(f"    {alias} = protocol.load_labware('{opentrons_name}', {slot})")
            loaded_labware[alias] = {
                "name": opentrons_name,
                "slot": slot,
            }

        elif op.op == IROpType.LOAD_INSTRUMENT:
            name = op.name
            opentrons_name = op.opentrons_name
            mount = op.mount
            tipracks_str = ", ".join([f"{tr}" for tr in (op.tipracks or [])])
            script.append(
                f"    {name} = protocol.load_instrument('{opentrons_name}', '{mount}', tip_racks=[{tipracks_str}])"
            )
            loaded_instruments[name] = {
                "mount": mount,
                "tipracks": op.tipracks or [],
            }

        elif op.op == IROpType.PICK_UP_TIP:
            pipette = op.pipette
            script.append(f"    {pipette}.pick_up_tip()")

        elif op.op == IROpType.DROP_TIP:
            pipette = op.pipette
            script.append(f"    {pipette}.drop_tip()")

        elif op.op == IROpType.ASPIRATE:
            pipette = op.pipette
            volume = op.volume_ul or 0
            source = parse_well_location(op.source, loaded_labware)
            script.append(f"    {pipette}.aspirate({volume}, {source})")

        elif op.op == IROpType.DISPENSE:
            pipette = op.pipette
            volume = op.volume_ul or 0
            destination = parse_well_location(op.destination, loaded_labware)
            script.append(f"    {pipette}.dispense({volume}, {destination})")

        elif op.op == IROpType.MIX:
            pipette = op.pipette
            repetitions = op.repetitions or 3
            volume = op.volume_ul or 10
            location = parse_well_location(op.location, loaded_labware)
            script.append(f"    {pipette}.mix({repetitions}, {volume}, {location})")

        elif op.op == IROpType.DELAY:
            seconds = op.delay_seconds or 60
            script.append(f"    protocol.delay(seconds={seconds})")

        elif op.op == IROpType.SET_TEMPERATURE:
            temp = op.temperature_c or 37
            script.append(f"    # Set module temperature to {temp}°C")

        elif op.op == IROpType.INCUBATE:
            seconds = op.delay_seconds or 300
            script.append(f"    protocol.delay(seconds={seconds})  # Incubation")

    return "\n".join(script)


def parse_well_location(location: str, loaded_labware: dict) -> str:
    """
    Parse a location string (e.g., "plate/A1") to Opentrons format.

    Args:
        location: Location string like "plate/A1"
        loaded_labware: Dictionary of loaded labware aliases

    Returns:
        Opentrons API call string like "plate['A1']"
    """

    if not location:
        return "None"

    if "/" not in location:
        return location

    parts = location.split("/")
    if len(parts) != 2:
        return location

    rack_alias, well = parts
    return f"{rack_alias}['{well}']"


def save_script(script: str, output_path: str):
    """Save compiled script to file."""

    with open(output_path, "w") as f:
        f.write(script)


def format_opentrons_code(script: str) -> str:
    """Format Opentrons code with basic linting."""

    # Simple formatting: ensure consistent indentation
    lines = script.split("\n")
    formatted = []

    for line in lines:
        if line.strip():
            # Count existing indentation
            indent_count = len(line) - len(line.lstrip())
            # Re-indent to 4-space multiples
            if "def " in line:
                formatted.append(line)
            else:
                stripped = line.strip()
                formatted.append("    " + stripped)
        else:
            formatted.append("")

    return "\n".join(formatted)


def add_safety_comments(script: str) -> str:
    """Add inline safety comments to the script."""

    lines = script.split("\n")
    annotated = []

    for i, line in enumerate(lines):
        annotated.append(line)

        # Add comments for key operations
        if "pick_up_tip" in line:
            annotated.append("    # Ensure tip is clean and properly seated")

        elif "aspirate" in line:
            annotated.append("    # Check source has sufficient volume")

        elif "dispense" in line:
            annotated.append("    # Verify destination well not overfilled")

        elif "drop_tip" in line:
            annotated.append("    # Tip should be empty before dropping")

    return "\n".join(annotated)


def validate_generated_code(script: str) -> list:
    """
    Basic validation of generated code.

    Returns:
        List of issues (empty if valid)
    """

    issues = []

    # Check for imports
    if "from opentrons import protocol_api" not in script:
        issues.append("Missing required import: from opentrons import protocol_api")

    # Check for metadata
    if "metadata" not in script:
        issues.append("Missing metadata definition")

    # Check for run function
    if "def run(protocol" not in script:
        issues.append("Missing run function definition")

    # Check basic syntax
    if script.count("{") != script.count("}"):
        issues.append("Mismatched braces")

    if script.count("[") != script.count("]"):
        issues.append("Mismatched brackets")

    if script.count("(") != script.count(")"):
        issues.append("Mismatched parentheses")

    return issues
